![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
print(my_array)
print(my_array[-1:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [21]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [29]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [27]:
ejer4 = np.arange(1,21).reshape(4, 5)
print(ejer4)

ejer4_1 = ejer4.transpose()

ejer4_1 = ejer4_1[::-1,::-1]

ejer4_1

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 15, 10,  5],
       [19, 14,  9,  4],
       [18, 13,  8,  3],
       [17, 12,  7,  2],
       [16, 11,  6,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [32]:
ejer5 = ejer4

ejer5[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [33]:
ejer6 = ejer4

ejer6[0::2,0::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [34]:
ejer7 = ejer4

ejer7[0:3:,-1::-1]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [154]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

y = x[np.isin(x, ["Loro"])]

    



In [153]:
x[ x =="Loro"]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [164]:
ejer9 = np.arange(20)
ejer9

ejer9.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [173]:
ejer10 = ejer4

ejer10[-1::-1,-1::-1]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [180]:
ejer11 = np.full(10,0)
ejer11
ejer11[3] = 1
ejer11

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [185]:
ejer12 = np.arange(10,50)
ejer12

ejer12[-1::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [20]:
vector = np.array([1,2,0,0,4,0])

vector = np.nonzero(vector)

vector

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [36]:
x = np.random.randint(9, size=(10,10))

x.min()
x.max()

np.int64(8)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [47]:
vec = np.random.randint(30, size=(30,))

vec = np.mean(vec)
print(vec)


16.366666666666667


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [41]:
u= np.ones((10,10))
u[1:-1:,1:-1:] = 0

print(u)

cuadrado = np.zeros((10,10))
cuadrado[0,:] = 1
cuadrado[-1,:] = 1
cuadrado[:,-1:] = 1
cuadrado[:,0] = 1

cuadrado

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [44]:
mtriz = np.zeros((8,8), dtype=int)
mtriz[0::2,1::2]=1
mtriz[1::2,0::2]=1
mtriz


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [137]:
ejer_18 = np.array([[0,1],[1,0]])

resultado = np.tile(ejer_18,(4,4))
print(resultado)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [75]:
np.random.seed(42)

ejer9 = np.random.randint(9, size=(5,5) )
ejer9_1 = ejer9 - np.mean(ejer9)
ejer9_1 = ejer9_1 / np.std(ejer9_1)
ejer9_1

array([[ 0.74759043, -0.52671144,  1.17235772, -0.10194415,  0.74759043],
       [-0.95147873,  0.74759043,  1.17235772, -0.10194415, -0.52671144],
       [ 1.17235772,  1.17235772, -0.95147873,  0.32282314, -0.10194415],
       [-1.37624602,  1.17235772,  0.32282314, -1.37624602, -0.10194415],
       [-1.80101331,  0.32282314,  1.59712502, -1.80101331, -0.95147873]])

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
numeros = np.arange(11)
numeros2 = numeros
numeros2[3:9] = -1

numeros2

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')